// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD95rYElXz30Eda2CWQg4MmgPHv2t0d8Dc',
    appId: '1:179855928704:web:2069936a6d8ff494892565',
    messagingSenderId: '179855928704',
    projectId: 'belajar-382bb',
    authDomain: 'belajar-382bb.firebaseapp.com',
    databaseURL: 'https://belajar-382bb-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-382bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtzBFVMa309fYfZpK78UGKt8US78-adI',
    appId: '1:179855928704:android:a648a22aaf39a436892565',
    messagingSenderId: '179855928704',
    projectId: 'belajar-382bb',
    databaseURL: 'https://belajar-382bb-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-382bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOEX6O_TPoR6nSTuLeu02ALBuo92fdO4',
    appId: '1:179855928704:ios:7ad429e6dba21b70892565',
    messagingSenderId: '179855928704',
    projectId: 'belajar-382bb',
    databaseURL: 'https://belajar-382bb-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-382bb.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxOEX6O_TPoR6nSTuLeu02ALBuo92fdO4',
    appId: '1:179855928704:ios:7ad429e6dba21b70892565',
    messagingSenderId: '179855928704',
    projectId: 'belajar-382bb',
    databaseURL: 'https://belajar-382bb-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-382bb.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD95rYElXz30Eda2CWQg4MmgPHv2t0d8Dc',
    appId: '1:179855928704:web:4cb9ca6417abfa6e892565',
    messagingSenderId: '179855928704',
    projectId: 'belajar-382bb',
    authDomain: 'belajar-382bb.firebaseapp.com',
    databaseURL: 'https://belajar-382bb-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-382bb.firebasestorage.app',
  );
}
