// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMfwl1a68DAwkPHOJ0-ZVLowXPqqAi9C8',
    appId: '1:1068146226144:web:1f8f7789d5956bdc173185',
    messagingSenderId: '1068146226144',
    projectId: 'notes-f9956',
    authDomain: 'notes-f9956.firebaseapp.com',
    storageBucket: 'notes-f9956.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUN2ch09FxrnB-XovZc_YQfvpMuEYDo3k',
    appId: '1:1068146226144:android:b620b60254028f8a173185',
    messagingSenderId: '1068146226144',
    projectId: 'notes-f9956',
    storageBucket: 'notes-f9956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4f9KbW9lwELtGu4c8_gPZues26CFK6ac',
    appId: '1:1068146226144:ios:5653471a9771800d173185',
    messagingSenderId: '1068146226144',
    projectId: 'notes-f9956',
    storageBucket: 'notes-f9956.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4f9KbW9lwELtGu4c8_gPZues26CFK6ac',
    appId: '1:1068146226144:ios:5653471a9771800d173185',
    messagingSenderId: '1068146226144',
    projectId: 'notes-f9956',
    storageBucket: 'notes-f9956.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMfwl1a68DAwkPHOJ0-ZVLowXPqqAi9C8',
    appId: '1:1068146226144:web:d06f2005b231918a173185',
    messagingSenderId: '1068146226144',
    projectId: 'notes-f9956',
    authDomain: 'notes-f9956.firebaseapp.com',
    storageBucket: 'notes-f9956.firebasestorage.app',
  );
}
