// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCOBcjOj2Iz8AvWcp0FI2XWEEpRU2L64',
    appId: '1:304352043490:web:e94210dda9b1f34b6fd9bb',
    messagingSenderId: '304352043490',
    projectId: 'daftarbelanja-cd4c2',
    authDomain: 'daftarbelanja-cd4c2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-cd4c2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-cd4c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRCkvjUn-zfbgQ1vj_DvPGXnOfDNO5Ac',
    appId: '1:304352043490:android:8b731d1f1b21c1166fd9bb',
    messagingSenderId: '304352043490',
    projectId: 'daftarbelanja-cd4c2',
    databaseURL: 'https://daftarbelanja-cd4c2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-cd4c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMVBBXn3AFVdvi8vnalwCQo1cO1K5dNk',
    appId: '1:304352043490:ios:9d3801e2d449682f6fd9bb',
    messagingSenderId: '304352043490',
    projectId: 'daftarbelanja-cd4c2',
    databaseURL: 'https://daftarbelanja-cd4c2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-cd4c2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMVBBXn3AFVdvi8vnalwCQo1cO1K5dNk',
    appId: '1:304352043490:ios:9d3801e2d449682f6fd9bb',
    messagingSenderId: '304352043490',
    projectId: 'daftarbelanja-cd4c2',
    databaseURL: 'https://daftarbelanja-cd4c2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-cd4c2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCOBcjOj2Iz8AvWcp0FI2XWEEpRU2L64',
    appId: '1:304352043490:web:3e70ead17648fb166fd9bb',
    messagingSenderId: '304352043490',
    projectId: 'daftarbelanja-cd4c2',
    authDomain: 'daftarbelanja-cd4c2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-cd4c2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-cd4c2.firebasestorage.app',
  );
}
