// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9v0Z_YbASNLTxnAKqgVb52nk0Srq78HE',
    appId: '1:373804451938:web:4a238555ec90ce2313e93b',
    messagingSenderId: '373804451938',
    projectId: 'mdpgold-69ae2',
    authDomain: 'mdpgold-69ae2.firebaseapp.com',
    databaseURL: 'https://mdpgold-69ae2-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-69ae2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGX-O0t8ohwNe9zLvBVMWD2wSHHHijORY',
    appId: '1:373804451938:android:e10963971675e7a113e93b',
    messagingSenderId: '373804451938',
    projectId: 'mdpgold-69ae2',
    databaseURL: 'https://mdpgold-69ae2-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-69ae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6yIH6faL19CqiBJ9-GJay-wS6oI2FmM',
    appId: '1:373804451938:ios:e9841bf54cbeb17213e93b',
    messagingSenderId: '373804451938',
    projectId: 'mdpgold-69ae2',
    databaseURL: 'https://mdpgold-69ae2-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-69ae2.firebasestorage.app',
    iosBundleId: 'com.example.mdpgold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu6yIH6faL19CqiBJ9-GJay-wS6oI2FmM',
    appId: '1:373804451938:ios:e9841bf54cbeb17213e93b',
    messagingSenderId: '373804451938',
    projectId: 'mdpgold-69ae2',
    databaseURL: 'https://mdpgold-69ae2-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-69ae2.firebasestorage.app',
    iosBundleId: 'com.example.mdpgold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9v0Z_YbASNLTxnAKqgVb52nk0Srq78HE',
    appId: '1:373804451938:web:729a65f98ab1ead113e93b',
    messagingSenderId: '373804451938',
    projectId: 'mdpgold-69ae2',
    authDomain: 'mdpgold-69ae2.firebaseapp.com',
    databaseURL: 'https://mdpgold-69ae2-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-69ae2.firebasestorage.app',
  );
}
