// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqUb03KnuX1hSkQZfjFSfiQwci_chjWs',
    appId: '1:50462271102:web:f383ac7bb30666d7be9a2f',
    messagingSenderId: '50462271102',
    projectId: 'mdpgold-ace92',
    authDomain: 'mdpgold-ace92.firebaseapp.com',
    databaseURL: 'https://mdpgold-ace92-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-ace92.firebasestorage.app',
    measurementId: 'G-X7J49PFFEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiRzZ47P6OlMfqk3I_Xv3Ivyvhz_62NgU',
    appId: '1:50462271102:android:1db424594512e958be9a2f',
    messagingSenderId: '50462271102',
    projectId: 'mdpgold-ace92',
    databaseURL: 'https://mdpgold-ace92-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-ace92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdsveN_loXqE5OKTOevRMZQ4FCop7qas',
    appId: '1:50462271102:ios:2bfe7dc3c5cbc8bdbe9a2f',
    messagingSenderId: '50462271102',
    projectId: 'mdpgold-ace92',
    databaseURL: 'https://mdpgold-ace92-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-ace92.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFdsveN_loXqE5OKTOevRMZQ4FCop7qas',
    appId: '1:50462271102:ios:2bfe7dc3c5cbc8bdbe9a2f',
    messagingSenderId: '50462271102',
    projectId: 'mdpgold-ace92',
    databaseURL: 'https://mdpgold-ace92-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-ace92.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsqUb03KnuX1hSkQZfjFSfiQwci_chjWs',
    appId: '1:50462271102:web:a65d7d9eb2b15ac7be9a2f',
    messagingSenderId: '50462271102',
    projectId: 'mdpgold-ace92',
    authDomain: 'mdpgold-ace92.firebaseapp.com',
    databaseURL: 'https://mdpgold-ace92-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-ace92.firebasestorage.app',
    measurementId: 'G-2MFZZWNRQF',
  );
}
